name: CI
on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Install client
        working-directory: ./client
        run: yarn install
      - name: Run client tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./client
          start: yarn start
          wait-on: 'http://localhost:3000'
